application:
  api-version: /v1
  api-prefix: /simple_car_lease/api
  cores:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_car_lease?useUnicode=true&characterEncoding=utf-8
    username: simple_car_lease
    password: simple_car_lease_passwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: NON_NULL

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
